# Generated by Django 2.2.1 on 2019-10-01 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='massage',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='userid',
            new_name='user_id',
        ),
    ]
